apiVersion: operator.in-cluster.crossplane.io/v1alpha1
kind: Operator
metadata:
  name: my-project-quay
  namespace: default
spec:
  providerConfigRef:
    name: provider-in-cluster
  forProvider:
    channel: stable
    operatorName: rh-quay-operator
    catalogSource: krishchow-catalog-source
    catalogSourceNamespace: openshift-marketplace