apiVersion: database.in-cluster.crossplane.io/v1alpha1
kind: Postgres
metadata:
  name: "postgresdb"
spec:
  forProvider:
    database: "test"
    databaseSize: "1Gi"
    storageClass: "standard"
    masterUsername: "testuser"
  providerConfigRef:
    name: "provider-in-cluster"
  writeConnectionSecretToRef:
    name: "out-secret"
    namespace: "default"
